//go:build embed

package web

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	htmlpkg "html"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip API routes
		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" || !s.fileExists(cleanPath) {
			s.serveIndexHTML(c)
			return
		}

		// Try local override first
		if s.tryServeOverride(c, cleanPath) {
			return
		}

		// Serve static files normally (hashed assets get long-lived cache headers)
		applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	profile := synthAPIMetadataForPath(c.Request.URL.Path)
	cacheKey := profile.CacheKey

	// Check cache first
	cached := s.cache.Get(cacheKey)
	if cached != nil {
		// Check If-None-Match for 304 response
		if match := c.GetHeader("If-None-Match"); match == cached.ETag {
			c.Status(http.StatusNotModified)
			c.Abort()
			return
		}

		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)

		c.Header("ETag", cached.ETag)
		c.Header("Cache-Control", "no-cache") // Must revalidate
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Preserve route-specific metadata even if public settings are unavailable.
		content := replaceNoncePlaceholder(injectSynthAPIMetadata(s.baseHTML, profile), nonce)
		c.Header("Cache-Control", "no-cache")
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		content := replaceNoncePlaceholder(injectSynthAPIMetadata(s.baseHTML, profile), nonce)
		c.Header("Cache-Control", "no-cache")
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	rendered = injectSynthAPIMetadata(rendered, profile)
	s.cache.Set(cacheKey, rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)

	cached = s.cache.Get(cacheKey)
	if cached != nil {
		c.Header("ETag", cached.ETag)
	}
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

type synthAPIMetadata struct {
	CacheKey    string
	Title       string
	Description string
	Canonical   string
	Robots      string
	Heading     string
	Answer      string
	SchemaType  string
}

const synthAPIOrigin = "https://synthapi.ecobim.club"

var synthAPIGuideMetadata = map[string]synthAPIMetadata{
	"quick-start": {
		Title:       "SynthAPI 快速开始：创建 API Key 并完成第一条请求",
		Description: "从注册、创建 API Key 到完成第一条兼容 OpenAI 的模型请求，按步骤验证权限、分组、渠道与用量记录。",
		Heading:     "SynthAPI 五分钟快速开始",
		Answer:      "创建 SynthAPI API Key 后，将客户端 base URL 指向站点的 /v1 接口，并使用当前分组已启用的模型。请求成功后还应在用量记录中核对模型、状态和费用。",
	},
	"concepts": {
		Title:       "SynthAPI 用户、分组、渠道与上游账号的关系",
		Description: "理解 SynthAPI 的用户权限、分组路由、渠道地址和上游账号四层关系，快速定位模型不可用问题。",
		Heading:     "SynthAPI 的四个核心对象",
		Answer:      "在 SynthAPI 中，用户决定权限，分组决定可用模型与路由规则，渠道描述上游地址和平台类型，上游账号提供实际凭据。四层共同决定一次请求能否被调度。",
	},
	"user-guide": {
		Title:       "SynthAPI 用户指南：API Key、模型、余额与用量",
		Description: "SynthAPI 普通用户如何创建 API Key、选择模型、查看余额、订阅状态与请求用量。",
		Heading:     "SynthAPI 普通用户指南",
		Answer:      "普通用户在 SynthAPI 控制台管理 API Key、查看当前可用模型，并通过余额、订阅和用量记录核对请求是否成功计费。每个应用和环境应使用独立 Key。",
	},
	"admin-guide": {
		Title:       "SynthAPI 管理员指南：账号、渠道、分组和计费",
		Description: "SynthAPI 管理员如何配置上游账号、渠道、模型分组、倍率与连接性监控。",
		Heading:     "SynthAPI 管理员配置指南",
		Answer:      "管理员应按上游账号、渠道、分组和用户权限的顺序建立可控路由，并分别检查凭据、模型白名单、倍率、并发和监控状态。只配置模型而没有可用渠道仍会返回 503。",
	},
	"api-reference": {
		Title:       "SynthAPI API 接入指南：兼容 OpenAI 的调用示例",
		Description: "使用 OpenAI SDK 接入 SynthAPI，配置 base URL、API Key、模型、流式输出和常见错误处理。",
		Heading:     "SynthAPI OpenAI-compatible API 接入",
		Answer:      "多数 OpenAI SDK 接入 SynthAPI 时只需把 base URL 改为 https://synthapi.ecobim.club/v1，并使用 SynthAPI API Key。模型名必须来自当前可用模型列表，流式调用需设置合理的读取超时。",
	},
	"billing": {
		Title:       "SynthAPI 余额、订阅和用量记录如何对账",
		Description: "区分可用余额、冻结金额、订单状态和请求用量，定位支付成功但额度未到账或扣费争议。",
		Heading:     "SynthAPI 余额与用量对账",
		Answer:      "SynthAPI 的可用余额、冻结金额和累计用量是不同口径。请求完成后应以用量记录中的模型、输入输出、媒体数量和最终费用为准；支付问题则另行核对订单与异步回调状态。",
	},
	"monitoring": {
		Title:       "SynthAPI 渠道监控：连通性与能力探测",
		Description: "使用 SynthAPI 渠道监控区分 DNS、TLS、HTTP 连通性与真实模型能力，降低无意请求和探测成本。",
		Heading:     "SynthAPI 渠道监控",
		Answer:      "仅连通性探测检查 DNS、TLS、HTTP 状态和耗时，不提交真实生成任务；能力探测会验证鉴权、模型和响应格式，可能产生费用，必须使用受控账号、模型和频率。",
	},
	"updates": {
		Title:       "SynthAPI 官方源码同步与定制保护",
		Description: "SynthAPI 如何同步 Sub2API 官方版本、保留部署定制，并在候选镜像通过健康检查后切换生产容器。",
		Heading:     "SynthAPI 更新与回滚机制",
		Answer:      "SynthAPI 更新器在隔离工作树中同步 Sub2API 官方版本并重放受保护定制，随后构建候选镜像。只有定制守卫、版本检查和容器健康检查全部通过，才会切换生产服务。",
	},
	"troubleshooting": {
		Title:       "SynthAPI 503、524 和流式请求断开排查",
		Description: "区分 SynthAPI 无可用账号、上游超时和流式连接断开，按模型、分组、渠道、账号与代理逐层排查。",
		Heading:     "SynthAPI 503 与 524 排查",
		Answer:      "SynthAPI 返回 503 通常表示目标分组没有可调度上游，需检查模型、分组、渠道、账号状态和冷却；524 通常表示代理已连接站点，但上游未在等待窗口内返回。",
	},
	"security": {
		Title:       "SynthAPI 安全与隐私：API Key、日志和数据边界",
		Description: "安全管理 SynthAPI API Key、上游凭据、日志、支付回调和客户数据，发生泄露时及时轮换与审计。",
		Heading:     "SynthAPI 安全与隐私",
		Answer:      "每个应用和环境应使用独立 SynthAPI API Key，并将其视为密码管理。工单、截图和公开 Issue 不应包含 Authorization 头、Cookie、上游 token、完整 prompt 或客户敏感数据。",
	},
}

func synthAPIMetadataForPath(requestPath string) synthAPIMetadata {
	path := strings.TrimSuffix(strings.TrimSpace(requestPath), "/")
	if path == "" || path == "/home" {
		return synthAPIMetadata{
			CacheKey: "home", Title: "SynthAPI - 多模型 AI API 网关",
			Description: "SynthAPI 是面向开发者与团队的多模型 AI API 网关，提供统一 API Key、兼容 OpenAI 的接口、渠道路由、用量计费和故障诊断。",
			Canonical:   synthAPIOrigin + "/home", Robots: "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1",
			Heading:    "SynthAPI 多模型 AI API 网关",
			Answer:     "SynthAPI 通过统一 API Key 和兼容 OpenAI 的接口接入并管理多种 AI 模型，提供渠道路由、用量计费、运行监控和故障诊断。SynthAPI 基于 Sub2API 开源项目构建并持续维护。",
			SchemaType: "SoftwareApplication",
		}
	}
	if path == "/about" {
		return synthAPIMetadata{
			CacheKey: "about", Title: "SynthAPI 是什么：产品、开源关系与能力边界",
			Description: "了解 SynthAPI 与 Sub2API 的关系、多模型 AI API 网关能力、第三方依赖和不作出的服务承诺。",
			Canonical:   synthAPIOrigin + "/about", Robots: "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1",
			Heading:    "SynthAPI 是什么",
			Answer:     "SynthAPI 是基于 Sub2API 开源项目构建并持续维护的独立服务品牌。它提供统一 API Key、协议适配、渠道路由、计量和运维能力，但不训练或拥有上游模型，也不隶属于模型提供商。",
			SchemaType: "AboutPage",
		}
	}
	if path == "/guide" {
		return synthAPIMetadata{
			CacheKey: "guide", Title: "SynthAPI 产品手册与 API 使用指南",
			Description: "SynthAPI 产品文档中心，包含快速开始、API 接入、账号与渠道管理、计费、监控、安全和 503/524 排查。",
			Canonical:   synthAPIOrigin + "/guide", Robots: "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1",
			Heading:    "SynthAPI 产品手册",
			Answer:     "SynthAPI 产品手册面向普通用户、管理员和开发者，提供创建 API Key、调用模型、配置渠道、核对计费、监控运行状态和排查 503/524 的分步说明。",
			SchemaType: "CollectionPage",
		}
	}
	if path == "/model-plaza" {
		return synthAPIMetadata{
			CacheKey: "model-plaza", Title: "SynthAPI 可用模型与渠道",
			Description: "查看 SynthAPI 当前公开的模型、渠道说明和价格信息；实际可用范围取决于用户权限、分组和上游状态。",
			Canonical:   synthAPIOrigin + "/model-plaza", Robots: "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1",
			Heading:    "SynthAPI 可用模型",
			Answer:     "SynthAPI 模型广场展示站点当前公开的模型和渠道说明。列表不构成永久可用承诺，实际调用仍取决于 API Key 权限、分组配置、账号额度和上游状态。",
			SchemaType: "CollectionPage",
		}
	}
	if strings.HasPrefix(path, "/guide/") {
		section := strings.TrimPrefix(path, "/guide/")
		if profile, ok := synthAPIGuideMetadata[section]; ok {
			profile.CacheKey = "guide-" + section
			profile.Canonical = synthAPIOrigin + path
			profile.Robots = "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"
			profile.SchemaType = "TechArticle"
			return profile
		}
	}
	return synthAPIMetadata{
		CacheKey: "private", Title: "SynthAPI",
		Description: "SynthAPI 用户与管理页面。",
		Canonical:   synthAPIOrigin + "/home", Robots: "noindex,nofollow,noarchive",
		Heading: "SynthAPI", Answer: "此页面属于 SynthAPI 的登录、用户或管理功能，不作为公开搜索内容。",
		SchemaType: "WebPage",
	}
}

func injectSynthAPIMetadata(html []byte, profile synthAPIMetadata) []byte {
	escape := htmlpkg.EscapeString
	schema := map[string]any{
		"@context":    "https://schema.org",
		"@type":       profile.SchemaType,
		"name":        profile.Title,
		"description": profile.Description,
		"url":         profile.Canonical,
		"isPartOf":    map[string]any{"@type": "WebSite", "name": "SynthAPI", "url": synthAPIOrigin + "/home"},
	}
	schemaJSON, _ := json.Marshal(schema)
	metadata := `<meta name="description" content="` + escape(profile.Description) + `" />` +
		`<meta name="robots" content="` + escape(profile.Robots) + `" />` +
		`<link rel="canonical" href="` + escape(profile.Canonical) + `" />` +
		`<meta property="og:type" content="website" />` +
		`<meta property="og:site_name" content="SynthAPI" />` +
		`<meta property="og:title" content="` + escape(profile.Title) + `" />` +
		`<meta property="og:description" content="` + escape(profile.Description) + `" />` +
		`<meta property="og:url" content="` + escape(profile.Canonical) + `" />` +
		`<meta name="twitter:card" content="summary" />` +
		`<script nonce="` + NonceHTMLPlaceholder + `" type="application/ld+json">` + string(schemaJSON) + `</script>`

	result := removeSynthAPIDefaultMetadata(html)
	result = bytes.Replace(result, []byte("</head>"), []byte(metadata+"</head>"), 1)
	result = replaceTitle(result, profile.Title)
	fallback := `<main data-synthapi-public-fallback="true"><h1>` + escape(profile.Heading) + `</h1><p>` + escape(profile.Answer) + `</p>` +
		`<nav aria-label="SynthAPI 公开内容"><a href="/home">产品首页</a> <a href="/about">产品与开源关系</a> <a href="/guide">产品手册</a> <a href="/guide/api-reference">API 接入</a> <a href="/guide/troubleshooting">故障排查</a></nav></main>`
	result = removeElementByMarker(result, `<main data-synthapi-public-fallback="true">`, `</main>`)
	return bytes.Replace(result, []byte(`<div id="app">`), []byte(`<div id="app">`+fallback), 1)
}

func removeElementByMarker(html []byte, marker, closingTag string) []byte {
	start := bytes.Index(html, []byte(marker))
	if start == -1 {
		return html
	}
	endOffset := bytes.Index(html[start:], []byte(closingTag))
	if endOffset == -1 {
		return html
	}
	end := start + endOffset + len(closingTag)
	return append(html[:start], html[end:]...)
}

func removeSynthAPIDefaultMetadata(html []byte) []byte {
	patterns := []string{
		`<meta name="description"`, `<meta name="robots"`, `<link rel="canonical"`,
		`<meta property="og:type"`, `<meta property="og:site_name"`, `<meta property="og:title"`,
		`<meta property="og:description"`, `<meta property="og:url"`, `<meta name="twitter:card"`,
	}
	result := html
	for _, pattern := range patterns {
		for {
			start := bytes.Index(result, []byte(pattern))
			if start == -1 {
				break
			}
			endOffset := bytes.IndexByte(result[start:], '>')
			if endOffset == -1 {
				break
			}
			result = append(result[:start], result[start+endOffset+1:]...)
		}
	}
	return result
}

func replaceTitle(html []byte, title string) []byte {
	start := bytes.Index(html, []byte("<title>"))
	end := bytes.Index(html, []byte("</title>"))
	if start == -1 || end == -1 || end <= start {
		return html
	}
	replacement := []byte("<title>" + htmlpkg.EscapeString(title) + "</title>")
	return append(append(append([]byte{}, html[:start]...), replacement...), html[end+len("</title>"):]...)
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Apply custom branding before the browser paints the static defaults.
	result = injectSiteTitle(result, settingsJSON)
	result = injectSiteFavicon(result, settingsJSON)

	return result
}

// injectSiteFavicon replaces the static favicon with a configured, browser-safe image URL.
func injectSiteFavicon(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteLogo string `json:"site_logo"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}

	logoURL := safeImageURL(cfg.SiteLogo)
	if logoURL == "" {
		return html
	}

	linkStart := bytes.Index(html, []byte(`<link rel="icon"`))
	if linkStart == -1 {
		return html
	}
	linkEndOffset := bytes.IndexByte(html[linkStart:], '>')
	if linkEndOffset == -1 {
		return html
	}
	linkEnd := linkStart + linkEndOffset + 1
	replacement := []byte(`<link rel="icon" href="` + htmlpkg.EscapeString(logoURL) + `" />`)

	var buf bytes.Buffer
	buf.Write(html[:linkStart])
	buf.Write(replacement)
	buf.Write(html[linkEnd:])
	return buf.Bytes()
}

func safeImageURL(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ""
	}
	if strings.HasPrefix(trimmed, "/") && !strings.HasPrefix(trimmed, "//") {
		return trimmed
	}
	if strings.HasPrefix(strings.ToLower(trimmed), "data:image/") {
		return trimmed
	}

	parsed, err := url.Parse(trimmed)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return ""
	}
	return trimmed
}

// injectSiteTitle replaces the static <title> in HTML with the configured site name.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil || cfg.SiteName == "" {
		return html
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return html
	}

	newTitle := []byte("<title>" + htmlpkg.EscapeString(cfg.SiteName) + " - AI API Gateway</title>")
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.Write(newTitle)
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			// Try local override first
			if tryServeOverrideFile(c, overrideDir, cleanPath) {
				return
			}
			applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		serveIndexHTML(c, distFS)
	}
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/models" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		trimmed == "/alpha/search" ||
		strings.HasPrefix(trimmed, "/images/") ||
		strings.HasPrefix(trimmed, "/videos/")
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
